# Generated by Django 6.0.3 on 2026-03-27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="timelog",
            name="approval_note",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="timelog",
            name="approval_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")],
                default="approved",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="timelog",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="timelog",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_time_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="timelog",
            name="entry_type",
            field=models.CharField(choices=[("auto", "Auto Timer"), ("manual", "Manual Entry")], default="auto", max_length=10),
        ),
        migrations.AddField(
            model_name="timelog",
            name="idle_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="timelog",
            name="is_billable",
            field=models.BooleanField(default=True),
        ),
    ]
