# Generated by Django 6.0.3 on 2026-03-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_timelog_approval_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="redirect_url",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
