# Generated by Cursor on 2026-03-30

from django.db import migrations
from django.utils.text import slugify


def forwards(apps, schema_editor):
    Team = apps.get_model("core", "Team")
    User = apps.get_model("core", "User")
    Project = apps.get_model("core", "Project")

    default_name = "Default Team"
    default_code = "default-team"

    team = Team.objects.filter(code=default_code).first()
    if team is None:
        team = Team.objects.create(name=default_name, code=default_code, created_by=None)

    # Backfill users first.
    User.objects.filter(team__isnull=True).update(team=team)
    # Backfill projects.
    Project.objects.filter(team__isnull=True).update(team=team)


def backwards(apps, schema_editor):
    # Keep data as-is on reverse; no safe way to unassign.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_team_project_team_user_team"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]

